spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: group_id
    topic:
      name: simple-message
  jackson:
    serialization:
      INDENT_OUTPUT: true
  h2:
    console:
      enabled: true
      path: /console
  datasource:
    url: jdbc:h2:mem:kafkadb;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: root
    password: root